name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build ${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: windows
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          echo "Building for $GOOS/$GOARCH"
          mkdir -p dist/${GOOS}-${GOARCH}
          go build -v -o dist/${GOOS}-${GOARCH}/luffy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luffy-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/${{ matrix.os }}-${{ matrix.arch }}/luffy
